### ISSUE TITLE
Cannot reset passwords.

### ISSUE THREAD

**Issue by trigat** [wazuh/wazuh-kubernetes#170]
I've been looking at guides and it looks like it's not possible to reset the 'kibanaserver' password with the current setup of the wazuh-kibana deployment @ kibana-deploy.yaml.

There is no persistent volume specified.  Documentation shows that after updating internal_users.yml, you have to update the filebeat.yml and kibana.yml files.  Since the kibana.yml file is in a deployment without a persistent volume, it changes back to the default password of 'kibanauser' once the pod restarts.  This causes the application to not start up properly.  Am I supposed to be updating kibana.yml at a location other than /usr/share/kibana/config/kibana.yml?

Here is how I am updating the internal_users.yml:

**kubectl exec -it -n wazuh wazuh-elasticsearch-0 -- bash -c "chmod +x /usr/share/elasticsearch/plugins/opendistro_security/tools/securityadmin.sh && /usr/share/elasticsearch/plugins/opendistro_security/tools/securityadmin.sh -f /usr/share/elasticsearch/plugins/opendistro_security/securityconfig/custom_internal_users.yml -t internalusers -nhnv -cacert /usr/share/elasticsearch/config/root-ca.pem -cert /usr/share/elasticsearch/config/admin.pem -key /usr/share/elasticsearch/config/admin-key.pem -icl -h localhost"**

Then filebeat.yml and kibana.yml:

**kubectl exec -it -n wazuh wazuh-manager-master-0 -- bash -c "sed -i 's/SecretPassword/NEWPASS/g' /etc/filebeat/filebeat.yml"
kubectl exec -it -n wazuh wazuh-kibana-XXX -- bash -c "sed -i 's/password: kibanaserver/password: NEWPASS/g' /usr/share/kibana/config/kibana.yml"**

Should a persistent volume be created for wazuh-kibana?

**Comment by teddytpc1** [comment]
The scenario has been tested, the Kibana deployment does not persist the changes as expected.
Some options where tested:
- Add PV and PVC objects.
- Configure Kibana deployment to use that PV and mount it in /usr/share/kibana
This approach has a conflict with the volumes mounted for the certificates because of the mount path.
To solve that issue a configMap must be created (along with a kibana.yml) and the PV mount path should be changed to point to the kibana.yml absolute path. This will be configured and tested tomorrow.

**Comment by teddytpc1** [comment]
Hi @trigat ,
An alternative for the `PV` for the Kibana deployment is to use a `ConfigMap` in order to provide the `kibana.yml` to de Kibana Pod. With this approach the `sed` command to update the password for Kibana should be executed with the `kibana.yml` located in the `wazuh-kubernetes` repository. For example:
`sed -i 's/password: kibanaserver/password: NEWPASS/g' wazuh/elastic_stack/kibana/kibana_conf/kibana.yml`

And after that the deployment has to be applied again. This will generate a new Kibana pod with the updated `kibana.yml`.

Changes in the manifests (you can use branch 170-add-persistent-volume for reference):
- Modify the [kustomization.yml](https://github.com/wazuh/wazuh-kubernetes/blob/170-add-persistent-volume/wazuh/kustomization.yml) to add the configMap:
``` 
  - name: kibana-conf
    files:
      - elastic_stack/kibana/kibana_conf/kibana.yml
``` 

- Add [kibana.yml](https://github.com/wazuh/wazuh-kubernetes/blob/170-add-persistent-volume/wazuh/elastic_stack/kibana/kibana_conf/kibana.yml) in `wazuh/elastic_stack/kibana/kibana_conf/` directory.
- Modify [kinaba-deploy.yaml](https://github.com/wazuh/wazuh-kubernetes/blob/170-add-persistent-volume/wazuh/elastic_stack/kibana/kibana-deploy.yaml) to add the configMap reference:
``` 
            - name: config
              mountPath: /usr/share/kibana/config/kibana.yml
              subPath: kibana.yml
              readOnly: false
```

**Comment by alberpilot** [comment]
I proceed to close this issue due to inactivity. Please don't hesitate to open it again if necessary.
