### ISSUE TITLE
Release v4.2.1 Kubernetes

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-kubernetes#180]
- [x] Merge Latest changes into 4.2.0
- [x] Test 4.2 Branch
- [x] Create 4.2.0 tag
- [x] Draft release

**Comment by teddytpc1** [comment]
I have been analyzing the repository to understand the manifests. Tomorrow I will deploy Wazuh 4.2.0 then make the required changes for 4.2.1 and test that version as well when the docker images are available.

**Comment by teddytpc1** [comment]
I have updated the repository to use Wazuh 4.2.1 instead of 4.2.0.
I was not able to test the deployment because the docker images are not available in docker hub yet.

**Comment by teddytpc1** [comment]
Docker images are not ready yet. We have had some issues when testing the docker compose deployment.

**Comment by teddytpc1** [comment]
We were unable to push the images with the Wazuh account so @vcerenu pushed them to his DockerHub account in order to test the K8s deployment.
I created a new cluster and deployed the Wazuh stack successfuly. Had to open Kibana console with Firefox because with Chrome I had the following message:
![Screenshot from 2021-09-13 17-09-47](https://user-images.githubusercontent.com/33964202/133149686-616fc894-99cb-4bdb-b21f-f77a146d6e3f.png)
And testing with curl the following message:
`Please upgrade your browser</h2><div class="kbnWelcomeText">This Elastic installation has strict security requirements enabled that your current browser does not meet`

This is the evidence of the successful deployment:
`kubectl get deployments -n wazuh
`||||||
|--|--|--|--|--|
|NAME|           READY|   UP-TO-DATE |  AVAILABLE|   AGE| 
|wazuh-kibana  | 1/1     |1            |1          | 37m|

` kubectl get services -n wazuh
` |||||||
|--|--|--|--|--|--|
|NAME                  |TYPE           |CLUSTER-IP       |EXTERNAL-IP                                                                       |PORT(S)                          |AGE|
|elasticsearch         |LoadBalancer   |10.100.105.44    |domain1-492704146.us-west-1.elb.amazonaws.com            |9200:31739/TCP                   |37m|
|kibana                |LoadBalancer   |10.100.46.178    |domain2-738690382.us-west-1.elb.amazonaws.com            |443:31764/TCP                    |37m|
|wazuh                 |LoadBalancer   |10.100.92.155    |domain3-1095712136.us-west-1.elb.amazonaws.com           |1515:31022/TCP,55000:31188/TCP   |37m|
|wazuh-cluster         |ClusterIP      |None             |<none>                                                                            |1516/TCP                         |37m|
|wazuh-elasticsearch   |ClusterIP      |None             |<none>                                                                            |9300/TCP                         |37m|
|wazuh-workers         |LoadBalancer   |10.100.244.218   |internal-domain4-567420246.us-west-1.elb.amazonaws.com   |1514:31291/TCP                   |37m|
 
` kubectl get statefulsets -n wazuh
`||||
|--|--|--|
|NAME                   |READY   |AGE|
|wazuh-elasticsearch    |3/3     |45m|
|wazuh-manager-master   |1/1     |44m|
|wazuh-manager-worker   |2/2     |44m|


` kubectl get pods -n wazuh
` ||||||
|--|--|--|--|--|
|NAME                            |READY   |STATUS    |RESTARTS   |AGE|
|wazuh-elasticsearch-0           |1/1     |Running   |0          |46m|
|wazuh-elasticsearch-1           |1/1     |Running   |0          |45m|
|wazuh-elasticsearch-2           |1/1     |Running   |0          |44m|
|wazuh-kibana-69dcd6b99c-ktv5b   |1/1     |Running   |0          |25m|
|wazuh-manager-master-0          |1/1     |Running   |0          |46m|
|wazuh-manager-worker-0          |1/1     |Running   |0          |46m|
|wazuh-manager-worker-1          |1/1     |Running   |0          |46m|

Kibana Console:
![Screenshot from 2021-09-13 17-05-12](https://user-images.githubusercontent.com/33964202/133151438-0c75a8ac-6216-4340-830b-39239ce85d9b.png)

Kibana Console - Wazuh Status:
![Screenshot from 2021-09-13 17-25-01](https://user-images.githubusercontent.com/33964202/133151522-d3b198be-93cf-475f-aa3e-982ae3f82237.png)

**Comment by teddytpc1** [comment]
I was able to test the deployment with the images pushed with the correct tag and everything worked fine.
I will continue with the merge and tag creation.

**Comment by teddytpc1** [comment]
I was able to test the deployment with the images pushed with the correct tag and everything worked fine.
I will continue with the merge and tag creation.

**Comment by teddytpc1** [comment]
I was able to test the deployment with the images pushed with the correct tag and everything worked fine.
I will continue with the merge and tag creation.

**Comment by teddytpc1** [comment]
I have already created the tag and the draft release.

**Comment by teddytpc1** [comment]
I have already created the tag and the draft release.

**Comment by alberpilot** [comment]
Completed. Thanks
