### ISSUE TITLE
wazuh deployment on kubernetes with ingress controller.

### ISSUE THREAD

**Issue by khasim4A2** [wazuh/wazuh-kubernetes#186]
Hi, here in this repository wazuh-kubernetes, its given like to deploy all the services with loadbalancer type. But i'm looking to use my ingress controller instead of individual load balancer for each service. Can some one please help me how can i achieve that. Facing 502 bad gate way if i'm routing the traffic with ingress controller.

**Comment by c-bordon** [comment]
Hi Khasim, I have been reviewing your issue and I think it is an improvement that we can apply to our repository, we are going to add it to our backlog to work on it in the future.

In the meantime, I can suggest the following:
I'm going to assume that you are working in AWS with a EKS cluster:
You mentioned that you already have an ingress controller, so what you should do is modify the services:
wazuh/elastic_stack/kibana/kibana-svc.yaml
wazuh/wazuh_managers/wazuh-master-svc.yaml
wazuh/wazuh_managers/wazuh-workers-svc.yaml
wazuh/elastic_stack/elasticsearch/cluster/elasticsearch-api-svc.yaml

These services are exposed through a Load Balancer, you should change them to the NodePort type and then create the ingress resources so that all these services use your ingress controller.
https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource

This is an example of Service:
https://raw.githubusercontent.com/kubernetes-sigs/aws-alb-ingress-controller/v1.1.4/docs/examples/2048/2048-service.yaml
This is an example of an Ingress Resource:
https://raw.githubusercontent.com/kubernetes-sigs/aws-alb-ingress-controller/v1.1.4/docs/examples/2048/2048-ingress.yaml

These were obtained from the AWS documentation:
https://aws.amazon.com/blogs/opensource/kubernetes-ingress-aws-alb-ingress-controller/

**Comment by alberpilot** [comment]
I proceed to close this issue due to inactivity. Please don't hesitate to re-open again if necessary.
