### ISSUE TITLE
Creating a storage-class for Wazuh?

### ISSUE THREAD

**Issue by echo-devnull** [wazuh/wazuh-kubernetes#271]
I tried running the kustomize into a test cluster, and the first error is:

```
❯ k apply -k .
namespace/wazuh created
error: error validating ".": error validating data: ValidationError(StorageClass): missing required field "provisioner" in io.k8s.api.storage.v1.StorageClass; if you choose to ignore these errors, turn validation off with --validate=false
```

So I have two questions;
The storageclass definition is indeed missing a provisioner. Which makes sense, since wazuh would not know beforehand what kind of options are available in the desired cluster. Which leads me to the second remark:

Why are we creating a storage class in the first place? Why not leave that empty so kubernetes will use the default storage class as defined by the cluster admin?

**Comment by markmaas** [comment]
I removed the storage class from this setup, after which it runs fine:

```
❯ k apply -k .
namespace/wazuh unchanged
configmap/dashboard-conf-gc2hkg4tff created
configmap/indexer-conf-765k99m7g8 created
configmap/wazuh-conf-9hf9g2fgk8 created
secret/dashboard-certs-mtfhfckgb8 created
secret/dashboard-cred created
secret/indexer-certs-d6dthm7chg created
secret/indexer-cred created
secret/wazuh-api-cred created
secret/wazuh-authd-pass created
secret/wazuh-cluster-key created
service/dashboard created
service/indexer created
service/wazuh created
service/wazuh-cluster created
service/wazuh-indexer created
service/wazuh-workers created
deployment.apps/wazuh-dashboard created
statefulset.apps/wazuh-indexer created
statefulset.apps/wazuh-manager-master created
statefulset.apps/wazuh-manager-worker created
```

So really, I'm just asking why it's in there? If it's not needed I'll create a PR to remove it.

**Comment by vcerenu** [comment]
Hello @echo-devnull 

The default storage class in new k8s environments usually has a **reclaim policy** in **delete**, which means that when you have to delete a deploy or statefulset for updating, for example, this deletes the associated PVs. The storage class that is created is to prevent this, since the PVs created with this **Storage Class** have the **retain** status as a **reclaim policy**, so as not to have problems with the need to disarm the deployment of the entire application.

Can you share with me what provisioners you have available and what type of cluster you are using? the deployment of our environment is made for two options: **local**, which would be to deploy on minikube or microk8s, and the **EKS** option on AWS
