### ISSUE TITLE
Adding documentation about modifying default credentials

### ISSUE THREAD

**Issue by NathanRodet** [wazuh/wazuh-kubernetes#332]
Hi,
It seems the Kubernetes deployment is lacking documentation or tools to modify default credentials while deploying.
Is it possible to provide a clear documentation part about it ? Thank you, have a great day

**Comment by vcerenu** [comment]
Hello @NathanRodet 

Thanks for letting us know, we are always trying to add important information to our documentation.
In the case of the documentation for changing the default credentials before deployment, I can provide you with the documentation referring to [Docker](https://documentation.wazuh.com/current/deployment-options/docker/wazuh-container.html#change-the-password-of-an-existing-user), which uses the same Docker images for the deployment of the Wazuh stack with some modifications:
- In step 3, instead of modifying the file `single-node/config/wazuh_indexer/internal_users.yml` you must modify the file `wazuh/indexer_stack/wazuh-indexer/indexer_conf/internal_users.yml`
- In step 4, instead of looking for the occurrences of the `INDEXER_PASSWORD` environment variable in the `docker-compose.yml` file, you must look for them in the corresponding secret within the `wazuh/secrets/` path and encoding the string in base64 with the following command :
```
echo -n "newpassword" | base64
```
#
If it is the first deployment, you can now deploy with the new modified passwords, if it is not the first deployment you will have to relaunch the `securityadmin.sh` script for the `Wazuh indexer` cluster, taking into account that this can delete all the configurations you have done and are not inside the internal_users.yml file.

**Comment by NathanRodet** [comment]
Hi, I followed the instruction.

- I generated a strong password.
- I base64 encoded it using the command `echo -n "newpassword" | base64`.
- I modified `wazuh/indexer_stack/wazuh-indexer/indexer_conf/internal_users.yml` on kibanaserver (assuming this was the wazuh dash user).
- I modified `wazuh/secrets/dashboard-cred.yaml` (assuming this was the wazuh dash user) with the hash produced by `docker run --rm -ti wazuh/wazuh-indexer:4.3.10 bash /usr/share/wazuh-indexer/plugins/opensearch-security/tools/hash.sh`.

And finally, I got an error : Wazuh dashboard server is not ready yet
And this error does not get out.
