### ISSUE TITLE
Problems loading configuration file

### ISSUE THREAD

**Issue by k86td** [wazuh/wazuh-kubernetes#339]
Hello, I'm trying to setup Wazuh on a baremetal k8s cluster, we've been able to set everything up, but after a certain condition, which we're incertain what it is, the permission of `filebeat.yml` changed, and it's impossible to change it back:
```
Exiting: error loading config file: config file ("/etc/filebeat/filebeat.yml") can only be writable by the owner but the permissions are "-rw-rw-r--" (to fix the permissions use: 'chmod go-w /etc/filebeat/filebeat.yml')
Filebeat exited. code=1
```

This error occurs on both the masters and the workers.

Here's some context. We've got 4 indexers, 3 masters and 4 workers
```
NAME                               READY   STATUS             RESTARTS         AGE
wazuh-dashboard-747fdbc448-xtcjc   1/1     Running            1 (5m36s ago)    3d17h
wazuh-indexer-0                    1/1     Running            1 (6m19s ago)    3d16h
wazuh-indexer-1                    1/1     Running            1 (5m43s ago)    3d16h
wazuh-indexer-2                    1/1     Running            1 (5m37s ago)    3d16h
wazuh-indexer-3                    1/1     Running            1 (6m12s ago)    3d16h
wazuh-manager-master-0             0/1     CrashLoopBackOff   940 (37s ago)    3d15h
wazuh-manager-master-1             0/1     CrashLoopBackOff   940 (101s ago)   3d15h
wazuh-manager-master-2             0/1     CrashLoopBackOff   942 (25s ago)    3d15h
wazuh-manager-worker-0             0/1     CrashLoopBackOff   974 (75s ago)    3d17h
wazuh-manager-worker-1             0/1     CrashLoopBackOff   976 (27s ago)    3d17h
wazuh-manager-worker-2             0/1     CrashLoopBackOff   975 (80s ago)    3d17h
wazuh-manager-worker-3             0/1     CrashLoopBackOff   974 (93s ago)    3d17h
```

I've tried to mount the volume on another pod and change the permission. Then I unmounted-remounted, the permission were still valid, but when I a master/worker mounts it, the permission becomes invalid.

Any help would be greatly appreciated.

**Comment by k86td** [comment]
Adding a InitContainer works, but I see it more as a hack than a fix. I'll keep this open if there's a more elegant solution.

**Comment by vcerenu** [comment]
Hello @k86td 

How are you mounting the filebeat.yml file inside the pod? via configmap?

In case you want to use a better option, within our entrypoint we have a [script](https://github.com/wazuh/wazuh-docker/blob/4.4/build-docker-images/wazuh-manager/config/etc/cont-init.d/1-config-filebeat) to modify the `filebeat.ym`l file, which modifies its parameters according to environment variables, which are set in the Wazuh manager deployment.
Inside that script we add the variables that we modify the most inside the `filebeat.yml` file, so if you need any more variables we can add it in a next release if you generate an issue in our repository [wazuh-docker](https://github.com/wazuh/wazuh- docker/issues).

In the case that you explain, you can use the variables that we already have set to change the path of `Wazuh indexer` to connect, username, password and some other parameters, let me know if they work for you and if it is necessary to add more, you can also do it by modifying the previous script and building your own images, since any changes we may have just for the next release.
