### ISSUE TITLE
Storage class-invalid

### ISSUE THREAD

**Issue by Chloe-Bo** [wazuh/wazuh-kubernetes#377]
Hello, 

I am trying to install Wazuh in Kubernetes so I was using :
https://documentation.wazuh.com/current/deployment-options/deploying-with-kubernetes/kubernetes-deployment.html
And when I use the command 
`kubectl apply -k envs/local-env/`
At the end I have : 
```
The StorageClass "wazuh-storage" is invalid:
* parameters: Forbidden: updates to parameters are forbidden.
* provisioner: Forbidden: updates to provisioner are forbidden.
* reclaimPolicy: Forbidden: updates to reclaimPolicy are forbidden.
* volumeBindingMode: Invalid value: "Immediate": field is immutable
```
And 

```
 $ kubectl get pods -n wazuh                                                                                                                                                                             [17:01]
NAME                               READY   STATUS    RESTARTS   AGE
wazuh-dashboard-57b4667dbd-wnjcs   1/1     Running   0          18m
wazuh-indexer-0                    0/1     Pending   0          18m
wazuh-manager-master-0             0/1     Pending   0          18m
wazuh-manager-worker-0             0/1     Pending   0          18m
 $ kubectl -n wazuh logs wazuh-indexer-0
Defaulted container "wazuh-indexer" out of: wazuh-indexer, volume-mount-hack (init), increase-the-vm-max-map-count (init)
```
Can you help me ? 

Thanks,

**Comment by vcerenu** [comment]
Hi @Chloe-Bo 

The error is due to some problem with the storage-class `wazuh-storage`, which is created in the deployment.
In the following [link](https://documentation.wazuh.com/current/deployment-options/deploying-with-kubernetes/kubernetes-deployment.html#setup-storage-class-optional-for-non-eks-cluster).
Clarify that for deployments in local environments it is necessary to update the `envs/local-env/storage-class.yaml` file with the provisioner that your cluster has, I ask you if you can verify this.

**Comment by teddytpc1** [comment]
Issue closed due to inactivity.
