### ISSUE TITLE
Add settings to make Kubernetes set up a local environment

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-kubernetes#49]
Hi team,

Currently, our k8s code only allows the installation using Amazon AWS, specifically [EKS](https://docs.aws.amazon.com/eks/) as stated in the [instructions.md](https://github.com/wazuh/wazuh-kubernetes/blob/master/instructions.md)

Deploying in a local machine can be really useful for development and testing purposes.

In order to achieve the said objective, the following tasks must be performed:

- [x] Adapt Deployments/StatefulSets to local mode
- [x] Add required settings to choose between EKS and Local
- [x] Flexibilize number of nodes and installation settings
- [x] Test 
- [x] Update CHANGELOG.md
- [x] Update README.md

Best regards,

Jose

**Comment by xr09** [comment]
There is support for a local minikube environment on the branch [feature-local-environment](https://github.com/wazuh/wazuh-kubernetes/tree/feature-local-environment).

A new wazuh namespace is created with 4 pods (wazuh, elastic, kibana, nginx). Both Wazuh and Nginx pods are exposed through NodePort on 31514,31514 and 30443 respectively.  (By default Minikube allows the range `30000-32767` for NodePorts).

![Screenshot_20200129_184924](https://user-images.githubusercontent.com/1380243/73382588-1287bf00-42c8-11ea-92f5-51d5b887028c.png)

Tested adding an agent, NodePorts communication is working fine.

![Screenshot_20200129_184944](https://user-images.githubusercontent.com/1380243/73382610-1ddaea80-42c8-11ea-98c2-3bec7c1c8ae6.png)

**Comment by xr09** [comment]
The new deployment procedure for this local environemnt is using `kustomization.yaml` a way of personalize a kubernetes deployment without having to apply each one of the files and allowing to modify its metadata directly from one yaml.

https://github.com/kubernetes-sigs/kustomize

This is a sample of our `kustomization.yaml`:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds wazuh namespace to all resources.
namespace: wazuh

# resources to apply
resources:
- base.yaml
- elastic/elasticsearch-svc.yaml
- elastic/elasticsearch-sts.yaml
- kibana/kibana-svc.yaml
- kibana/kibana-deploy.yaml
- kibana/nginx-svc.yaml
- kibana/nginx-deploy.yaml
- wazuh/wazuh-svc.yaml
- wazuh/wazuh-conf.yaml
- wazuh/wazuh-sts.yaml
```

Since release 1.14 kubernetes supports kustomization files to personalize deployments, the workflow is as simple as `kubectl apply -k .` on the `minikube` directory and all resources will be applied with the correct adjustments.
