### ISSUE TITLE
Version ahead of time?

### ISSUE THREAD

**Issue by julienkosinski** [wazuh/wazuh-kubernetes#555]
Hello everyone and happy new year! :)

Maybe it's because you're using a different repository but, with docker.io repository, version 4.9.0 of wazuh-manager, wazuh-dashboard, wazuh-indexer does not exist.

The latest unstable version of these images is currently 4.8.0-alpha1...

Also, about this file : https://github.com/wazuh/wazuh-kubernetes/blob/master/CHANGELOG.md
Version after 4.7.1 redirect to 404 pages.

Thank you very much!

**Comment by davidcr01** [comment]
Hello. The issue you are involved in is related to our branches and releases system. In this part of the [README.md](https://github.com/wazuh/wazuh-kubernetes/blob/master/README.md#branches) we specify that the `master` branch contains the latest code. It exists because it is needed to work in the new versions of Wazuh.

Currently, the `master` branch is the numbered branch `4.9.0`. Our latest tag is `v4.7.1`, you can check it here. https://github.com/wazuh/wazuh-kubernetes/releases/tag/v4.7.1. The `latest` tag in the release title indicates it. This is the most recent and stable version of Wazuh. The rest of the versions higher than it are being developed.

About the links of the CHANGELOG.md, we edit that file when we create a new version of Wazuh, and they throw a 404 error because that version of Wazuh is not released yet. When the related version is released, the links will work.

**Comment by julienkosinski** [comment]
Thank you very much for this explanation! :)
