### ISSUE TITLE
chown: unknown user/group root:wazuh

### ISSUE THREAD

**Issue by AishVinod** [wazuh/wazuh-kubernetes#778]
I am trying to integrate custom-urlhaus with wazuh deployed on kubernetes using this documentation https://wazuh.com/blog/detecting-malicious-urls-using-wazuh-and-urlhaus/

For kubernetes setup I have mounted custom-urlhaus.py into /var/ossec/integrations/custom-urlhaus.py. However in order to execute the scripts below permisisons and ownership is mandatory : 

chmod 750 /var/ossec/integrations/custom-urlhaus.py
chown root:wazuh /var/ossec/integrations/custom-urlhaus.py

Once I mount the files into pod, by default I see permission as below : 

-rw-r--r-- 1 root   101  5441 custom-urlhaus.py

I suppose group 101 is coming from below configuration is master-sts file : 

securityContext:
        fsGroup: 101

I tried adding initcontainer to execute the required script : 

initContainers:
        - name: volume-mount-hack
          image: busybox
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
          command:
            - sh
            - '-c'
            - 'chmod 750 /var/ossec/integrations/custom-urlhaus.py && chown root:wazuh /var/ossec/integrations/custom-urlhaus.py'

However I see inticontainer is failing with below errors :

chmod: /var/ossec/integrations/custom-urlhaus.py: Read-only file system
chown: unknown user/group root:wazuh 

Any help on how to update the needed permissions in cluster files would be appreciated.

**Comment by saraiva82** [comment]
I am seeing some issues with this with my integration as well. All files in the container are root:wazuh owned. if you run a ps in the container 
same 
![image](https://github.com/user-attachments/assets/06f288ab-54ed-4fca-8f12-a7b5df8522f5)
and
there does not seem to be a user 101 either
![image](https://github.com/user-attachments/assets/1af3bd35-bf0a-41b6-b604-42cf105c4252)

closest is some dude name games lol. now the wazuh user is 999 so wouldn't it make more sense to set that 
securityContext: to 
fsGroup: 999 instead?
anyways Im trying it out and  see if my cluster still works after

**Comment by AishVinod** [comment]
@saraiva82 Any luck on the same? I am still struggling for the same

**Comment by saraiva82** [comment]
Hey @AishVinod,  
so far the permissions issues seem to have resolved themselves
<img width="113" alt="image" src="https://github.com/user-attachments/assets/63dacd24-1c0e-42a5-a872-ee9909f65ca4">

and now when i use wazuh-logtester to debug my log I do not see the permissions errors that I was getting on my integrations and rules. So I think it resolved the issue even though im troubleshooting my log but now i think is a decoder thing and not this.

**Comment by vcerenu** [comment]
Hello @AishVinod 

Regarding mounting the necessary file, within the entrypoint of the Wazuh image we have a process which copies with the necessary permissions the files from the `/wazuh-config-mount/` directory to the `/var/ossec/` directory:

https://github.com/wazuh/wazuh-docker/blob/574c7b05c747499e6af31a1ba8a33abebee1f298/build-docker-images/wazuh-manager/config/etc/cont-init.d/0-wazuh-init#L134-L142

Let me know if mounting the file in that directory gives you a better result with the integration.

Regarding the FsGroup, we will analyze it to change it in a future release.

**Comment by ChestoOfGlen** [comment]
I am also experiencing this issue with trying to integrate our MISP instance in via the same custom Python script method.

We're mounting files into /wazuh-config-mount, and have even tried changing fsGroup to 999 (the Wazuh group).
![image](https://github.com/user-attachments/assets/378d4d4f-a655-42d0-ba2c-0e5646bf6926)

This causes files to mount with correct user:group in the /wazuh-config-mount but when the init script copies them to /var/ossec it seems to reset the permissions to root:root.

![image](https://github.com/user-attachments/assets/c1d006ed-53a5-44f3-8cbe-d46ac0ecc670)
![image](https://github.com/user-attachments/assets/3c3e6bc1-a18e-45ff-8c83-45412c8fb1d0)

As you can see in the screenshot, anything that exists as part of default Wazuh has correct permissions for root:wazuh, but things copied from /wazuh-config-mount have root:root.

From looking at the init script, it seems like the order of operations is a bit wrong.
![image](https://github.com/user-attachments/assets/e1c3426d-cc18-4213-995f-1a52cc8a5153)

The set_correct_permOwner function is run early on, which from the comments seems to be looking for old user and group IDs (101) which are specifically related to OSSEC, and changing them to 999 which is specifically the Wazuh group (and assumedly user).
![image](https://github.com/user-attachments/assets/defa6725-70c1-46f7-8c43-35bb26ae0175)

But then later on in the main function, mount_files is run which copies the files from /wazuh-config-mount into /var/ossec but because its running as root the copy action squashes the previous permissions back to root:root.
![image](https://github.com/user-attachments/assets/032f2d3e-0977-46f2-99ac-861892c07e3e)

Based on all this information, I an not sure that the /wazuh-config-mount method of mounting files to a K8s instance of Wazuh has ever worked for anything that actually requires the correct root:wazuh permissions.

Solutions for this, as I see it, are one of:
- Move the permissions function to the end of the init script, so it sets everything with the proper permissions after any configs, etc. have been mounted.
- Change fsGroup to 999 (instead of 101) and add either the -p switch or -a switch to the mount_files function to preserve permissions, etc. when copying from the config mount dir to the install location.
- Change fsGroup to 999 and directly mount the file/s you need into /var/ossec instead of mounting into /wazuh-config-mount
